// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cocfecxieqhzjxytmzpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvY2ZlY3hpZXFoemp4eXRtenBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzMzk3NDksImV4cCI6MjA0OTkxNTc0OX0.UkerSJ5r56oirUYCwHnbcFDpfeHFOgWMykjehTebPAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);